- README.md
**Audience**: Engineers | Third-party Developers
**Summary**: Add documentation to for developers to get started with `local-components`. This includes what it is, how to use, showing the folder structure, briefly explaining global vs. scoped style, development commands, a plug for the component demo and also for Add-on docs.
This is only the beginning of this documentation and it'll be ever evolving. It'd be nice to get down the tone we want this type of stuff to be in going forward. Straight up technical? A little playful?
> [LOC-200] local-components documentation

- src/components/Banner/Banner.sass
- src/components/Banner/README.md
- src/components/Spinner/Spinner.jsx
**Audience**: Users | Engineers | Third-party Developers
**Summary**: Banner's need to be able to support links inside them. This adds a scoped, color appropriate style for `<a />` tag descendants within the Banner component.
**Screenshots**: 
| Link      | Link Hover |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/41925404/50181787-f2b75680-02d2-11e9-97d5-157af30c6de9.png) | ![image](https://user-images.githubusercontent.com/41925404/50181830-0fec2500-02d3-11e9-811e-4a2c3c5148f8.png) |
> [LOC-236] add style for links in Banner component

- src/components/Spinner/Spinner.jsx
**Audience**: Engineers | Third-party Developers
**Summary**: The Spinner component's `color` PropType `oneOf` was incorrectly setup to take string params instead of an array of strings.
> fix: properly pass array for <Spinner />'s color prop definition

- src/components/Divider/Divider.jsx
- src/components/Divider/README.md
- src/components/FlyTooltip/FlyTooltip.jsx
- src/components/FlyTooltip/FlyTooltip.sass
- src/components/RadioBlock/README.md
- src/components/RadioBlock/RadioBlock.jsx
- src/components/RadioBlock/RadioBlock.sass
- src/styles/_partials/_selectors.scss
- src/styles/containers/SiteInfo.scss
- src/styles/forms.scss
- src/styles/util.scss
**Audience**: Users  | Engineers | Third-party Developers
**Summary**: The purpose of this PR is to add component props and styles to RadioBlock to support switching between staging and production when pushing/pulling within `flywheel-local`. In addition to this, a number of other components and globals styles were added and/or modified to meet the requirements of the design.
**Technical**: 
- added disabled, heightSize (medium is new), tooltip feature, and className support for RadioBlock
- added several Styleguidist examples for RadioBlock
- added widthIsAuto support for FlyTooltip and fixed a z-index issue
- added/refactored margin top support for Divider 
- added several global utility styles
- fixed form checkbox issue
> [LOC-197] Add radio block to choose between staging and production when pushing/pulling

- src/components/RadioBlock/RadioBlock.sass
- src/components/Truncate/Truncate.tsx
**Audience**: Users | Engineers
**Summary**: Updated RadioBlock padding and resize width to match designs and Truncate require to use default export.
**Technical**: Truncate bug is due to a third-party component with a `.d.ts` file that's not ideally exported. This was resulting in the following error: 
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `Truncate`.
```
> [LOC-197] Updated RadioBlock styles and Truncate require

- src/components/Avatar/Avatar.sass
- src/components/Avatar/Avatar.tsx
- src/components/Avatar/README.md
- src/components/Avatar/index.ts
- src/components/ClippedContent/ClippedContent.sass
- src/components/ClippedContent/ClippedContent.tsx
- src/components/ClippedContent/README.md
- src/components/ClippedContent/index.ts
- src/components/ImageCircle/ImageCircle.sass
- src/components/ImageCircle/ImageCircle.tsx
- src/components/ImageCircle/README.md
- src/components/VerticalNav/VerticalNav.sass
- src/components/VerticalNav/VerticalNav.tsx
- src/index.ts
**Audience:** Engineers | Third-party Developers
**Summary:** Added an `Avatar` component with image and initials visuals, team and user types, background colors, and sizes. To support this feature, a `ClippedContent` component has been created and the `ImageCircle` was modified to use `ClippedContent`.
> feat(LOC-221): add Avatar component

- src/components/FlyModal/FlyModal.tsx
- src/components/Spinner/README.md
- src/components/Spinner/Spinner.sass
- src/components/Spinner/Spinner.tsx
- src/styles/containers/SiteInfo.scss
**Summary:** Add text/children support for `<Spinner />`, use `onRequestClose` prop on `<FlyModal />` if provided. Some SCSS was also removed that should've been in Local itself.
----
> improvement(LOC-320): add text support to Spinner, use onRequestClose prop in FlyModal

- src/components/FlySelect/README.md
- src/styles/forms.scss
**Audience:** Users
**Summary:** Rather than hacking together css styles within `flywheel-local`, add support for the `Avatar` component within `FlySelect`.
**Technical:** All styles for the `FlySelect` component are still global, so it would be ideal to refactor this eventually and write in such a way that Avatars and other components work without any specific accommodations while moving to css modules.
**Out of scope:** The solution and screenshot example below shows a `FlySelect` within form elements which increases its size. Currently, the smallest `Avatar` is too large for the standard `FlySelect` and its size.
**Screenshots:** 
Original issue when using out-of-the-box:
The solution (as shown in Styleguidist):
> improvement(LOC-478): add Avatar option support for FlySelect

- src/components/FlyModal/FlyModal.sass
**Audience:** Users
**Summary:** Allow for more content within a modal by increasing max-height. This is a short-term fix for pulling/pushing to unconnected sites but makes sense long-term as well.
> fix(LOC-466): change max-height of FlyModal to accommodate more content

- src/components/RadioBlock/README.md
- src/components/RadioBlock/RadioBlock.sass
- src/components/RadioBlock/RadioBlock.tsx
**Audience:** Users | Developers
**Summary:** Added direction prop and vertical layout/styles to the Radio Block component. An example has been added to Styleguidist as well.
> improvement(LOC-505): add vertical layout to RadioBlock

- src/common/structures/ILocalContainerProps.ts
- src/components/Container/Container.scss
- src/components/Container/Container.tsx
- src/components/Container/ContainerMarginHelper.test.ts
- src/components/Container/ContainerMarginHelper.ts
- src/components/Header/Header.tsx
**Audience:** Engineers | Third-party Developers
**Summary:** Most components within the `local-components` package are wrapped in a container to allow for more flexibility (which allows for more style and layout flexibility while being able to more gracefully handle unplanned edge-cases). `Container` provides a predictable wrapper component, with a consistent API, and convenient way to access the Container's "shape" through a single `component` prop within the component utilizing it (e.g. Header).
The `Container` component also adds some extremely helpful and convenient props/features. One of those features is to disable/exclude the container DOM element if not being explicitly used. This is useful if you want the flexibility of using the container if needed without creating an …
> feat(LOC-556): create Container component with advanced margin expressions and auto disable feature

- src/components/Checkbox/Checkbox.tsx
- yarn.lock
**Summary:** The `<Checkbox />` component is passing the `disabled` prop straight into the state in `constructor` but not handling `disabled` in `componentWillReceiveProps`. Since `disabled` isn't changed in `<Checkbox />`, `disabled` has been removed from the state and will be passed as a prop only.
> fix(LOC-691): remove disabled from <Checkbox /> state and use prop only

- src/components/VirtualTable/VirtualTable.tsx
**Summary:** Add `overscan` to `<VirtualTable />` props instead of using a hard-coded value of `2000`.
> feat(LOC-695): add overscan to VirtualTable props

- src/components/BigLoader/BigLoader.tsx
- src/components/LoadingIndicator/LoadingIndicator.tsx
- src/components/LoadingIndicator/README.md
**Summary:** Add `dots` prop to `<LoadingIndicator />` and default it to `2`.
**Context:** We need to be able to use the three dot loading indicator with the small size.
> improvement(LOC-714): add dots prop to <LoadingIndicator />

- src/components/WindowsToolbar/WindowsToolbar.sass
**Summary:** Windows top bar covers up part of the workspace switcher.
**Outstanding Concerns:** There's a risk of unaccounted for elements with a z-index greater than `1` appearing above the WindowsToolbar. Some are by design (e.g. drag and drop, workspace switcher), but others might appear in unaccounted for scenarios like scrolling content.
**Screenshots:** 
(prior issue that's now fixed)
> fix(LOC-737): decrease WindowsToolbar z-index down to 1 to avoid competing with other views

- src/components/Container/Container.tsx
- src/components/Container/README.md
**Audience:** Engineers | Third Party Developers
**Summary:** The `Container` component allows for switching out the container element's tag, but adding support to switch out the entire container element opens up new possibilities for this component. Specifically, this feature will be used with RadioBlock to allow for wrapping options in Tooltips. In addition, documentation has been added to Container showing how to use it in a number of scenarios.
> feat(LOC-277): add element support for Container and create styleguidist examples

- package.json
- src/components/Tooltip/README.md
- src/components/Tooltip/Tooltip.scss
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/index.ts
- src/index.ts
- src/styles/_partials/_functions.scss
- src/styles/buttons.scss
- yarn.lock
**Audience:** Engineers | Third Party Developers
**Summary:** A new Tooltip component needs to be created to solve for two major problems that the existing FlyTooltip doesn't solve for:
1. don't wrap tooltip content in additional elements
2. when a tooltip runs out of screen real estate, it should reposition itself
One final objective with the new Tooltip component is to exclude any styles related to other components. Since scoped styles have been introduced, this has been increasingly important. As such, when replacing Flytooltip for Tooltip, several of those previously baked-in styles will have to be re-introduced using other patterns.
The underlying library chosen to make this happen is `popper.js` due to its features, flexibility, and popularity. In addition, popper is simply a …
> feat(LOC-277): create popper-based Tooltip component to replace FlyTooltip 

- src/components/RadioBlock/README.md
- src/components/RadioBlock/RadioBlock.sass
- src/components/RadioBlock/RadioBlock.tsx
**Audience:** Engineers | Third Party Developers
**Summary:** RadioBlock needs to support the newest Tooltip component. Rather than simply swapping out the internal dependency of FlyTooltip within RadioBlock, `local-components` Container component was introduced. This not only allows RadioBlock to leverage Container's built-in features (e.g. margin), but also allows any component or element to be a wrapper container for RadioBlock and RadioBlockOption thus eliminating a hard-coded dependency on a component like FlyTooltip.
RadioBlock also uses a number of z-indexes to display various graphics and selected states. To make this more maintainable and flexible, SASS variables have been added and a style has been added that assumes that any sibling to a RadioBlockOption is likely there as a …
> improvement(LOC-277): add container wrapper to RadioBlock to allow for easy implementation of Tooltip component

- src/components/Tooltip/Tooltip.scss
- src/components/Tooltip/Tooltip.tsx
**Audience:** Engineers | Third Party Developers
**Summary:** The tooltip needs to continue showing even after the mouse leaves the content reference and enters the actual tooltip. Furthermore, the tooltip shouldn't hide when moving back and forth between the two elements. 
**Technical:** A delay needed to be added to allow for the switching between the reference and tooltip/popper elements. From an interaction standpoint, a delay is a positive enhancement anyways so that delay has been increased to a 'natural feeling' number.
Slowed down interactions of intricate hover state sequences (1/10th normal speed):
http://flywheel.link/98d0d351d075
> fix(LOC-277): persist tooltip visibility when switching from reference to popper on hover

- src/components/Checkbox/Checkbox.sass
- src/styles/_partials/_theme.scss
- src/styles/_partials/_variables.scss
- src/styles/containers/Flywheel.scss
**Audience:** Users | Engineers | Third Party Developers
**Summary:** Add dark mode variant for Checkbox, adjust FlySite image filter style, and change non-input border styles to match their intended gray value to fix the workspace switcher divider issue for dark mode.
without dark mode variant:
with dark mode variant (improvement):
with dark mode disabled (improvement):
before FlySite image:
after FlySite image (with fix):
before divider: 
after divider (with border fix):
> fix(LOC-732, LOC-752): fix incorrect and missing component styles 

- src/components/FlyTooltip/FlyTooltip.scss
- src/components/Popup/Popup.sass
- src/components/Tooltip/Tooltip.scss
**Summary:** The WorkspaceSwitcher animation performance was poor on first reveal and sometimes subsequent calls to show and/or hide. This fix removes the filter effect as it was identified as the culprit.
**Technical:** `filter: drop-shadow...` was not playing nice with `transition` so it was replaced with `box-shadow`. Several style instances of transition and box shadow were changed in conjunction with this change. In addition, `will-change` has been added as a performance measure to Popup and Tooltip.
> fix: remove filter to fix slow WorkspaceSwitcher animation

- src/components/VerticalNav/README.md
- src/components/VerticalNav/components/WorkspaceSwitcher.scss
- src/components/VerticalNav/components/WorkspaceSwitcher.tsx
**Summary:** Setup WorkspaceSwitcher to support upgrade to pro option.
**Technical:**
- Remove existing teams option
- Add 'isPro' prop
- Check for any paid seat and only show upgrade option if none exists
**Out of Scope**:
- the design calls for the workspace avatars to be centered horizontally but that's not being accounted for in this story
Workspace Switcher with 'Upgrade To Pro' item
> improvement(LOC-898): upgrade to Pro in WorkspaceSwitcher

- src/components/ClippedContent/ClippedContent.sass
- src/components/VerticalNav/components/WorkspaceSwitcher.scss
**Audience:** Users | Engineers | Third-Party Developers
**Summary:** The workspace switcher is missing several hover states. This PR adds those styles while also adjusting the clip-path of avatars (via ImageCircle) to address alleged rounding issue that results in an unexpected y-start of the clip path.
Before clip-path fix:
After clip-path fix:
Inactive item (base vs hover):
Active item (base vs hover):
Add button (base vs hover):
> style(LOC-777): add hover states to workspace switcher and adjust clip-path of avatars

- package.json
- src/components/BrowseInput/BrowseInput.tsx
- yarn.lock
**Summary:** Use `untildify` instead of the `format-home-path` helper in Local. 
**Context:** `format-home-path` is in a different location in Lightning, thus breaking existing requires like the one this PR resolves. Going forward, `local-components` should _not_ require anything directly from Local.
> fix(LOC-972): use untildify instead of format-home-path to support Lightning

- package.json
- src/components/Animation/Animation.tsx
- src/components/Animation/README.md
- src/components/Animation/examples/AnimationExample.scss
- src/components/Animation/examples/AnimationExample.tsx
- src/components/Animation/examples/AnimationExample2.scss
- src/components/Animation/examples/AnimationExample2.tsx
- tslint.json
- yarn.lock
**Audience:** Engineers | Third-Party Developers
**Summary:** For more intricate transitions, a library is needed to simplify the mounting/unmounting of animations that require handling of states beyond simply start and end. This PR introduces examples for lists that animate in and out items as well as a slide in modal animation. These examples are under the menu item `Animation` for the time being.
**Out of Scope:** Components. This PR does not attempt to create a reusable component but rather proves out two scenarios and solutions where a library like `react-move` would be an asset for developers.
> feat(LOC-1043): add animation modal and list example using react-move

- src/components/Container/Container.tsx
- src/components/Header/Header.tsx
- src/components/TitleBar/README.md
- src/components/TitleBar/TitleBar.scss
- src/components/TitleBar/TitleBar.tsx
- src/components/TitleBar/index.ts
- src/index.ts
**Audience:** Third-party developers | Engineers
**Summary:** This adds an out-of-the-box TitleBar component for Add-on developers to easily implement while not having to worry about styles like font-sizes, font-weights, and dark mode text and background colors. The Local app also has several instances that could be refactored to use this component.
**Technical:** `TitleBar` takes a `title` prop as well as children content that will be right-aligned (if provided).
**Out of Scope:** In dark mode, several instances where this component is used have a border above it that's slightly lighter and creates a beveled look. This is not intentional and while a `margin-top: -1px` fix could resolve the issue, it's far from ideal to bake that into the base style of the component and thus has not been …
> feat(LOC-1155): create TitleBar component

- src/components/TitleBar/README.md
- src/components/TitleBar/TitleBar.scss
- src/components/TitleBar/TitleBar.tsx
**Summary:** The right-content font-weight styles are wrong, there's no spacing added to children, and an additional example with text and a link is needed.
**Screenshot:**
> fix(LOC-1155): update content styles and update examples

- src/common/helpers/ComponentExampleBase.tsx
- src/components/text/Text/Text.tsx
- src/components/text/Text/examples/TextExample.tsx
- src/components/text/Title/Title.tsx
- src/components/text/_private/TextBase/TextBase.scss
- src/components/text/_private/TextBase/TextBase.tsx
**Summary:** There were some discrepancies between the design and implementation for sizes and colors in addition to Text captions not being exposed publicly. This PR corrects those.
> fix(LOC-1162): correct text sizes, colors, and add captions for Text component

- src/components/buttons/Button/Button.tsx
- src/components/buttons/Button/examples/ButtonExample.tsx
**Summary:** Intents need to be reintroduced within the `Button` component with intended `fill` form and subsequent styles.
> fix(LOC-1158): add Button intents back in with expected 'fill' form

- src/components/text/Text/Text.tsx
**Audience:** Add-on Developers
**Summary:** Change default `size` prop option from `m` to `default` since there are no other t-shirt sizes for this component.
> refactor(LOC-1162): change Text size prop value from `m` to `default`

- src/components/buttons/Button/Button.tsx
**Summary:** Buttons styles for `alert` and `success` only exist for reversed/ghost appearance and that's not currently supported so those need to be removed.
**Screenshot:**
> fix(LOC-1158): remove Button intent styles `alert` and `success`

- src/components/alerts/Banner/Banner.sass
- src/styles/containers/Flywheel.scss
**Summary:** Remove global styles that are colliding with the new `Title` component being used within `flywheel-local`. Also tweaking the `Banner` button top and bottom padding.
> refactor(LOC-1220): remove global styles for sites that are no longer needed

- src/common/structures/IReactComponentProps.ts
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
**Summary:** Buttons need to support refs. This allows refs to be set by using `innerRef`.
**Out of Scope:** Wrapping each button component in `React.forwardRef`.
> improvement(LOC-1222): add innerRef support for button components

- src/components/buttons/_private/ButtonBase/ButtonBase.scss
- src/components/inputs/BrowseInput/BrowseInput.sass
- src/components/inputs/BrowseInput/BrowseInput.tsx
**Audience:** Users | Engineers | Add-on Developers
**Summary:** Fix inconsistent outline button styles for hover and disabled and tweak BrowseInput button margin.
**Screenshots:** 
Disabled outline button state:
Hover outline button state:
BrowseInput button margin-left tweak:
> fix(LOC-1273): fix outline button story and tweak browse input margin

- src/styles/_partials/_theme.scss
**Summary:** There's a bug where elements that explicitly set a theme mode such as `.Theme__Light` to ensure that theme colors are always applied the same regardless of the current global theme doesn't work if the selector applying the color (e.g. body) is an ancestor of the element setting the new theme mode (e.g. html.Theme__Dark body .Theme__Light).
**Screenshot:**
The bug:
The fix:
> fix(LOC-1302): add support to explicitly set theme mode on section with ancestor selector

- README.md
While skimming through the README, I noticed a spelling mistake that should be cleaned up!
In addition, I figured it wouldn't hurt to add some header links and a link to the `LICENSE` file to match the other `local-*` repos.
> Clean up some documentation

- src/common/structures/Generics.ts
- src/components/alerts/Banner/Banner.tsx
- src/components/buttons/Close/Close.tsx
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
- src/components/inputs/BrowseInput/BrowseInput.tsx
- src/components/inputs/Checkbox/Checkbox.tsx
- src/components/inputs/FlyDropdown/FlyDropdown.tsx
- src/components/inputs/FlySelect/FlySelect.tsx
- src/components/inputs/InputSearch/InputSearch.tsx
- src/components/inputs/RadioBlock/RadioBlock.tsx
- src/components/inputs/Switch/Switch.tsx
- src/components/loaders/DownloaderItem/DownloaderItem.tsx
- src/components/media/ImageCircle/ImageCircle.tsx
- src/components/menus/TertiaryNav/TertiaryNav.tsx
- src/components/modules/Card/Card.tsx
- src/components/modules/VerticalNav/components/WorkspaceSwitcher.tsx
- src/components/modules/WindowsToolbar/WindowsToolbar.tsx
- src/components/tables/TableListRepeater/TableListRepeater.tsx
- src/global.d.ts
Local Engineers | Add-on Developers
Add typings for FlySelect so setting props like `optionGroups` are easier to use and safe-guarded. Also export `FunctionGeneric` rather than using `global.d.ts` to overcome build issues within `flywheel-local`. 
- **NOJIRA**
- [LOC-1254](https://getflywheel.atlassian.net/browse/LOC-1254)
> improvement(LOC-1254): type FlySelect and cleanup errors

- src/components/inputs/FlySelect/FlySelect.tsx
- src/components/inputs/FlySelect/README.md
- src/styles/forms.scss
Users | Local Engineers | Third-Party Developers
* Adds a striped/alternate rows option to FlySelect via `striped` prop and adds the corresponding styles.
* Adds a styleguidist example to demonstrate alternate row colors which includes an option groups code example as part of it.
> improvement(LOC-1405): add striped row option to FlySelect and add example

- src/components/inputs/FlySelect/FlySelect.tsx
Local Engineers | Third Party Developers
Console warning for missing key.
This was caused by [this PR](https://github.com/getflywheel/local-components/pull/88).
> fix: add missing key for FlySelect empty span

- package.json
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
- src/components/inputs/InputPasswordToggle/InputPasswordToggle.tsx
- src/components/overlays/FlyModal/FlyModal.tsx
- src/index.ts
- tsconfig.json
Flywheel Engineers
To support flywheel-local enabling `strictNullChecks`, several typings, exports, and configs have to be modified or added.
See inline comments for the files changed and the reason why.
> chore(LOC-1528): enable strictNullChecks and refactor to resolve all issues

- README.md
- package.json
- src/components/modules/WindowsToolbar/README.md
- src/components/text/List/README.md
- styleguide.config.js
Developers
Replace all references to "by Flywheel" within the style guide.
Simple search and replace of static references used in non-critical documentation.
- [LOC-1699](https://getflywheel.atlassian.net/browse/LOC-1699)
> refactor(LOC-1699): remove all "by Flywheel" references

- src/components/layout/Divider/Divider.sass
- src/components/layout/Divider/Divider.scss
- src/components/layout/Divider/Divider.tsx
- src/components/layout/Divider/README.md
Local Engineers and Third Party Developers
Several components and design elements require an element or component to be vertically and horizontally centered within an <hr> tag. This PR adds support for this within the Divider component.
- if Divider implementation defines children, then a wrapper div is renderer children absolutely positioned to be vertically and horizontally centered
- Readme.md example added with simple badge
- converted Divider.sass to .scss
> feat(LOC-1451): render and layout children in middle of hr if defined for Divider

- src/components/inputs/InputSearch/InputSearch.tsx
This issue is causing a bug that is preventing me from finishing my current ticket. 
Basically when I clear the value prop, the input text does not update since it doesn't trigger the onChange event.
Here's a video demonstrating the bug: 
[Screen Recording 2020-04-09 at 4.40.11 PM.zip](https://github.com/getflywheel/local-components/files/4458764/Screen.Recording.2020-04-09.at.4.40.11.PM.zip)
> fix: Don't sync value prop to state.

- src/components/modules/VerticalNav/components/WorkspaceSwitcher.tsx
Local Engineers
The `WorkspaceSwitcher` UX is changing as a result of our transition to HUB. This makes some changes to accomodate that. Basic rules/logic (as discussed with Jack) is as follows:
**Has local_seat:**
- Display workspace switcher
- Hide “upgrade to pro”
- Display hub’s login/logout link
**Has hub_seat**
- Display workspace switcher if also has local_seat
- Display hub’s login/logout link
**No local_seat without hosts**
- Display “upgrade to pro”
- Display hub’s login/logout link
**No local_seat with hosts**
- Display “upgrade to pro”
- Display hub’s login/logout link
***Note*** that this dependent on [this PR](https://github.com/getflywheel/flywheel-local/pull/549) and [this PR](https://github.com/getflywheel/flywheel-local/pull/552)
- …
> feat: Update Workspace Switcher for transition to Hub

- src/styles/containers/AddSitePage.scss
All Local users
Show progress stepper when user adds a new site.
Remove 100% height and add flex: 1 to .AddSiteContent class.
> Show progress stepper during add site

- package.json
- src/components/buttons/CopyButton/CopyButton.scss
- src/components/buttons/CopyButton/CopyButton.tsx
- src/components/buttons/CopyButton/README.md
- src/components/buttons/CopyButton/_private/CopyButtonIcon.tsx
- src/components/buttons/CopyButton/examples/CopyButtonExample.tsx
- src/components/buttons/TextButton/TextButton.tsx
- src/components/buttons/_private/ButtonBase/ButtonBase.scss
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
- yarn.lock
Local devs and add-on developers
Some of our sweet new designs call for some new components including a `CopyButton` and a `LinkButton`. This adds a `CopyButton` component as well as exposing a new prop on `TextButton` that will allow it to be flexible enough to be used as a `LinkButton`.
I debated between using [clipboard-copy](https://github.com/feross/clipboard-copy), [clipboard.js](https://github.com/zenorocha/clipboard.js),
or rolling my own and landed on the first (`clipboard-copy`). It's tiny (433B) [according to Bundlephobia](https://bundlephobia.com/result?p=clipboard-copy@3.1.0). It attempts to use the Async Clipboard API and if not available falls back to `execCommand`.
Adds some additional `props` to `BaseButton` & `LinkButton` to allow for some more styling flexibility. This …
> feat(PRO-202): add CopyButton component and new style options to Text Button

- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
Creating this as a mandatory `prop` breaks `yarn build:webpack` and additionally, this shouldn't be required. Let's change that.
> fix(PRO-202): allow textTransform to be optional

- src/index.ts
`CopyButton` needs to be exported to make it available to the world 🌍
> fix(PRO-202): export CopyButton

- src/components/inputs/FlySelect/FlySelect.tsx
Local users
I added tabbing to the Add Site form but accidentally broke the ability to hide options when you click outside the component for FlySelect when I removed the onClickOutside function 🤦 
Per Clay's original suggestion on my previous PR, I moved the blur handler back to the parent div and added logic to only set state if a child div isn't focused.
- **NOJIRA**
> fix(flySelect): close options on outside click

- src/components/buttons/Close/Close.scss
- src/components/buttons/_private/ButtonBase/ButtonBase.scss
- src/components/inputs/BrowseInput/BrowseInput.sass
- src/components/inputs/RadioBlock/RadioBlock.sass
- src/components/layout/AdvancedToggle/AdvancedToggle.sass
- src/components/modules/InnerPaneSidebar/InnerPaneSidebar.sass
- src/components/tables/TableList/TableList.sass
- src/styles/_partials/_forms.scss
- src/styles/_partials/_mixins.scss
- src/styles/base.scss
- src/styles/components/Popup.scss
- src/styles/forms.scss
Local users
This PR adjusts focus styles so the default outline only shows if the 'using-mouse' class isn't added to the body. This impacts the entire app, so if the user tabs outside the Add Site form they will see default outlines. They will not see default outlines, however, if they click. Requires [this pr](https://github.com/getflywheel/flywheel-local/pull/581) to work.
If the 'using-mouse' class is added to the body then they outline style is set to none, otherwise the focus style is set to show the default outline. Outlines are still set to none by default.
- **NOJIRA**
> fix: link default outline with using-mouse class & adjust outline styles

- package.json
- src/components/modules/VerticalNav/components/WorkspaceSwitcher.tsx
Change "LOGIN" to "LOGIN TO HUB" in `<WorkspaceSwitcher />` to improve clarity.
This PR includes the version bump.
> feat(PRO-230): change "LOGIN" to "LOGIN TO HUB" in WorkspaceSwitcher

- package.json
- src/components/menus/TertiaryNav/TertiaryNav.tsx
- src/styles/_partials/_theme.scss
- yarn.lock
**Audience:**
Local Devs
**Summary:**
Need to bump up the react-router-dom version to match flywheel-local repository.
**Additions since PR:**
- Fix how withRouter is imported for react-router-dom 5.x
- Add theme back-ground mixin for handling light/dark theme within Pro Promo Section (see screenshots below)
> feat(PRO-239): Update react-router-dom version to match flywheel-local

- src/components/buttons/CopyButton/CopyButton.tsx
I mistakenly used `typeof` instead of `keyof typeof` in the `CopyButton` `props` interface. This causes a bunch of TS errors.
Here is a fix!
> fix: typeof -> keyof typeof

- azure-pipelines.yml
**Audience:** 
Developers referencing [the styleguide](https://getflywheel.github.io/local-components)
**Summary:**
Adjust CI steps for adding deploy key to fix a failure that was preventing Styleguidist from rebuilding on GitHub Pages.
> ci: change how secureFilepath is referenced for GitHub SSH key

- src/components/buttons/CopyButton/CopyButton.tsx
It turns out that `keyof typeof` requires enums to have exact matching `key` `value` pairs. Here is one more small fix to get this working correctly from a consumer standpoint.
> fix: Enums where key/value don't match blow up keyof typeof

- src/components/buttons/CopyButton/CopyButton.scss
- src/components/buttons/CopyButton/CopyButton.tsx
- src/components/overlays/Popup/Popup.sass
- src/components/overlays/Popup/Popup.tsx
- src/utils/cloneNodes.ts
The Popup component needed some love to make it more versatile and useable for Live Links UI. Here it is!
- Adds ability to toggle whether or not clicking the `Popup` contents will close the `Popup`
- Passes a handler function to child nodes that allow child components to close the `Popup`
- Fixes font size issue on Copy Button
- Adds a new util function to assist in cloning React nodes and shallow merging arbitrary props in with cloned nodes
> feat: add more "closing" configurability to Popup

- src/styles/containers/SiteInfo.scss
**Audience**
Local users.
**Summary**
Update the CSS for site info overview page; this fix allows live link popups to display properly without being cut off.
**Technical**
The `overflow` property of the overarching `SiteInfo` class was removed in favor of `min-width: 0`. This restricts the flexbox content from extending beyond the window size, but still allows "overflow" from elements such as the live link popups. [An extended explanation can be found here.](https://makandracards.com/makandra/66994-css-flex-and-min-width)
> fix(LOC-1905): correction to site info page so live link popups display properly

- package.json
- src/components/menus/TertiaryNav/TertiaryNav.sass
- src/components/menus/TertiaryNav/TertiaryNav.tsx
**Summary:**
Needed to update the TertiaryNav and TertiaryNavItem styling a bit.
- TertiaryNav to be a fixed 200px.
- When in Dark Mode and a TertiaryNavItem is selected there was no active background color -- changing this to be $gray-dark50
**Important**: If you want to test this via the Local app there are 2 other PRs coming, one for Flywheel-Local and one for Local-Addon-Broken-Link-Checker
> feat(PRO-260): Make TertiaryNav fixed width; change dark theme active nav item bg color

- src/utils/cloneNodes.ts
We're getting few warnings in the flavor of:
```
Warning: React does not recognize the `<propName>` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `<propname>` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
This is due to the `cloneNodes` function blindly merging in additional `props` with all nodes it is cloning. This can be avoided by only passing additional props to React components and NOT React elements.
Checking wether or not a `node` is a component or element was relatively straightforward once I understood how React represents these two entities. If you're curious to know more, I highly recommend [this …
> fix(PRO-340): don't pass down extra props to cloned nodes in cloneNodes

- package.json
- yarn.lock
`yarn link`ing this package with `flywheel-local` has been causing TS errors due to differing `@types/react` versions in this package, this package's deps and Local. The fix is to use Yarn `resolutions` to ensure that the same version is used for all packages involved.
> fix: yarn link issue

- src/components/buttons/CopyButton/CopyButton.scss
Local Users
Updates the CopyButton component to increase font weight and add additional right/left padding on the "Padding_Small" class variations.
One of two pull requests submitted for PRO-297; second PR located [here.](https://github.com/getflywheel/flywheel-local/pull/684)
Minor SCSS changes only.
- [PRO-297](https://getflywheel.atlassian.net/browse/PRO-297)
> refactor(PRO-297): styling changes to CopyButton component

- package.json
- src/components/menus/TertiaryNav/TertiaryNav.sass
- src/components/modules/SiteInfoInnerPane/SiteInfoInnerPane.sass
- src/components/modules/SiteInfoInnerPane/SiteInfoInnerPane.tsx
- fixes the Pro tab -> Instant Reload -> Info Tootip is hidden on Windows
- sneaks in a little class to function upgrade for `<SiteInfoPane />`
[PRO-486](https://getflywheel.atlassian.net/browse/PRO-486)
[Flywheel Local Sister PR](https://github.com/getflywheel/flywheel-local/pull/761)
> fix(PRO-486): windows style bugs

- src/components/text/Truncate/Truncate.test.tsx
- src/components/text/Truncate/Truncate.tsx
Summary
The Truncate component was failing to render content. This fix changes the import syntax and moves the id, className, and style props to the div instead of the third-party component.
> fix(LOC-2034): fix critical Truncate render bug

- src/components/overlays/FlyTooltip/FlyTooltip.test.tsx
- src/components/overlays/FlyTooltip/FlyTooltip.tsx
Site push/pull icon buttons width applied incorrectly to container.
Incorrectly applied `style` in [this PR](https://github.com/getflywheel/local-components/pull/134/files#diff-fc41e316a42ae3086c7dc5fa5b3f1f04R36). Need to move all of these out of the container and onto the primary component element. In addition, there were duplicate `className` props being applied (which is a problem waiting to happen) so the one on the container has been removed. If it's needed later, the `Container` component can be used or a `containerClassName` prop could be added as a quick fix.
Moving `className` always presents some risk. I ran through implementations to confirm there were no visual side effects, but it needs to be tested thoroughly for regressions.
- …
> fix(LOC-2127): fix flytooltip props

- src/index.ts
Linux build is failing because the TitleBar path is wrong in the module export.
Capitalize `TitleBar` directory correctly (was `Titlebar` 🙄)
- [Azure Build](https://dev.azure.com/localbyflywheel/Local%20by%20Flywheel/_build/results?buildId=4870&view=logs&j=641e4c04-9698-5c27-19e6-14023c1c3b0a&t=b59f18d2-c258-5720-387a-0cae1d6879fe)
- [LOC-2130](https://getflywheel.atlassian.net/browse/LOC-2130)
> fix(LOC-2130): fix cap issue with exported reference to TitleBar path

- package.json
- src/components/buttons/CopyButton/CopyButton.scss
- src/components/buttons/_private/ButtonBase/ButtonBase.scss
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
Local Pro Users
Fixes a handful of styling issues found on the LiveLinksPro pop up:
- Letter spacing on a number of buttons
- Adds better dark mode support for "CopyText" buttons
- Removes the HTTP auth username and password from the copy text on one of the buttons.
- Updates the .scss file for the "CopyButton" component to accommodate dark mode
- Adds a border to CopyButton component when dark mode is active
- Updates the ButtonBase component so it accepts a new privateOption "letterSpacing" and translates it to a CSS property.
- A few additional changes can be found in the corresponding PR for `flywheel-local`: https://github.com/getflywheel/flywheel-local/pull/807 
**Before updates**
**After updates**
Short gif recording to show hover states: https://i.getf.ly/lluYlW82
- …
> fix(PRO-291): fix LiveLinksPro popup styling bugs

- src/components/inputs/IconCheckbox/IconCheckbox.scss
- src/styles/_partials/_theme.scss
Local Engineers and Add-on Developers
IconCheckbox hover background color works on some backgrounds and not others for dark mode.
- change hover for dark mode to darker gray (aka black) that we don't use for backgrounds so it always appears
- [LOC-2112](https://getflywheel.atlassian.net/browse/LOC-2112)
> fix(LOC-2112): change dark mode hover color for IconCheckbox to work with any background

- src/components/inputs/IconCheckbox/IconCheckbox.scss
- src/components/inputs/IconCheckbox/IconCheckbox.stories.mdx
- src/components/inputs/IconCheckbox/IconCheckbox.tsx
- src/styles/_partials/_theme.scss
Local Engineers and Add-on Developers
IconCheckbox hover background color works on some backgrounds and not others for dark mode.
- change hover for dark mode to most commonly needed background color and add prop to use alternative for edge cases
- [LOC-2112](https://getflywheel.atlassian.net/browse/LOC-2112)
> fix(LOC-2112): fix IconCheckbox hover color and add alternative prop

- .storybook/preview-head.html
Theme has been changed on localwp.com. This updates a hotlink to it for Storybook
> fix: Update the font hotlink from localwp.com

- package.json
- src/components/menus/TertiaryNav/TertiaryNav.sass
Local Pro Users
This is a super small PR that updates the TertiaryContent class that was causing some CSS scrolling issues for Broken Link Checker.
Sister PR for flywheel-local here: https://github.com/getflywheel/flywheel-local/pull/875
Sister PR for Broken Link Checker here: getflywheel/local-addon-broken-link-checker#15
Adds a single line of scss that uses the `calc` feature to set max height for the `TertiaryContent` div. This is necessary to inform broken link checker containers what height to use for `max-height: 100%`.
**Pros:** 
- The code works
- It seems to be the most straightforward solution. An alternative would be to undergo a greater style refactor of the parent divs for TertiaryContent,  which could impact more areas of Local than just TertiaryContent and would require …
> fix(LOC-2202): allow link checker to scroll

- package.json
- src/components/alerts/Banner/Banner.sass
- src/components/alerts/Banner/Banner.tsx
**Summary:**
Per LOC-2150, when there are multiple banners within a carousel sometimes the banners were not the same height. Particularly if one banner had a button and the other did not have a button.
This change should make banners height more consistent regardless if the banner has a button or not.
For testing purposes you can yarn link this to Local and slap down some Banners -- I put the following within the SiteInfo index.
```
// import { BannerCarousel, Banner } from '@getflywheel/local-components'
<div>
<BannerCarousel>
<Banner variant="success" icon="warning" buttonText="Click Me!" buttonOnClick={() => console.log('buttonOnClick')}>
<strong>Typewriter!</strong> Poke selvage fam retro pug, offal butcher occupy banh mi artisan tousled. Poke selvage fam retro pug, offal
</Banner> …
```
> fix(LOC-2150): Up the min-height of Banner component

- src/components/inputs/FlySelect/FlySelect.tsx
- src/components/inputs/IconCheckbox/IconCheckbox.test.tsx
- src/components/inputs/IconCheckbox/IconCheckbox.tsx
- src/components/inputs/InputPasswordToggle/InputPasswordToggle.test.tsx
- src/components/inputs/InputPasswordToggle/InputPasswordToggle.tsx
Move id to input elements for `IconCheckbox` & `InputPasswordToggle` components so global click tracking will recognize it as an 'input' for analytics.
Add an id to the option in `FlySelect` to track when a user clicks the option for analytics.
Accompanies: [PR for LOC-2307]( https://github.com/getflywheel/flywheel-local/pull/903)
> Rearrange ID's for input click tracking

- src/components/buttons/_private/ButtonBase/ButtonBase.scss
Sync SVG color with text color in disabled outline buttons.
> fix: sync outline button SVG color with text color when disabled

- package.json
- src/components/loaders/ProgressRing/ProgressRing.scss
- src/components/loaders/ProgressRing/ProgressRing.stories.mdx
- src/components/loaders/ProgressRing/ProgressRing.test.tsx
- src/components/loaders/ProgressRing/ProgressRing.tsx
- src/index.ts
Create a new progress component that's circular (aka ring).
- create new `ProgressRing` component within the `progress` section of storybook
- use programmatic svgs to efficiently render circle instead of outdated css hacks like 360 separate lines, clip-path, etc
- document with several story examples
- add basic tests
- flatten all CSS to make it easier to override when consuming
- add non-hashed class names (in addition to locally scoped names used for styling) for easier selector access later on
- clamp progress so it must always resolve to 0-100
- little tweaks to rotation of circle and progress fill math to make it "look full" at 100% while taking into account the extra size adding by `stroke-linecap: round`
- some of the colors used are automatically changed depending on theme …
> feat(LOC-2380): add ProgressRing component

- .storybook/preview.js
- package.json
- src/common/helpers/Portal.tsx
- src/common/helpers/useDetectHover.ts
- src/common/helpers/useDetectTransitionEnd.ts
- src/common/helpers/useTimeout.ts
- src/components/overlays/Tooltip/Tooltip.scss
- src/components/overlays/Tooltip/Tooltip.stories.mdx
- src/components/overlays/Tooltip/Tooltip.tsx
- yarn.lock
This PR is intended to introduce non-breaking changes while introducing React Portals to overcome Tooltips getting clipped by overview containers. In addition, the `Tooltip` component was class-based and should be migrated over to a functional component that uses hooks.
- the very nature of adding React Portals changes a number of layout and css rules that might result in the tooltip shifting any number of pixels. This is due to the Tooltip no longer being next to the component in the DOM tree but rather being added as a child to the body element (via portals). These shifts in position have been attempted to be minimized.
- the overall style of the Tooltip should not have changed
- the various states required for the modified Tooltip have changed and there is now an addition delay stage …
> feat(LOC-2321): Change Tooltip to use React Portals and migrate to functional component

- README.md
- src/components/buttons/_private/ButtonBase/ButtonBase.test.tsx
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
- src/components/inputs/BasicInput/BasicInput.test.tsx
- src/components/inputs/BasicInput/BasicInput.tsx
- src/components/inputs/Checkbox/Checkbox.test.tsx
- src/components/inputs/Checkbox/Checkbox.tsx
- src/components/inputs/IconCheckbox/IconCheckbox.test.tsx
- src/components/inputs/IconCheckbox/IconCheckbox.tsx
- src/components/inputs/InputPasswordToggle/InputPasswordToggle.test.tsx
- src/components/inputs/InputPasswordToggle/InputPasswordToggle.tsx
- src/components/inputs/Switch/Switch.test.tsx
- src/components/inputs/Switch/Switch.tsx
Inputs and button-based components need to support the `name` attribute for forms.
* adds a `name` prop to 6 components and applies as attribute to underlying form item
* tests to confirm that `name` is applied correctly to the rendered component
* FlySelect doesn't use `select` behind the scenes and so it wasn't touched (though there might come a day when we have to rethink how that component is setup)
- [LOC-2618](https://getflywheel.atlassian.net/browse/LOC-2618)
> feat(LOC-2618): introduce name attribute for all the various input and button components

- .storybook/preview-head.html
- package.json
- src/components/icons/helpers/withIconSvg.tsx
- src/components/icons/svgs/CheckmarkMixedIcon.tsx
- src/components/layout/Accordion/Accordion.scss
- src/components/layout/Accordion/Accordion.stories.mdx
- src/components/layout/Accordion/Accordion.test.tsx
- src/components/layout/Accordion/Accordion.tsx
- src/components/layout/Accordion/AccordionItem.scss
- src/components/layout/Accordion/AccordionItem.stories.mdx
- src/components/layout/Accordion/AccordionItem.test.tsx
- src/components/layout/Accordion/AccordionItem.tsx
- src/index.ts
- yarn.lock
Create an Accordion component with:
- open/close action
- animation
- auto close any other items (optionally)
- default chevron
- stories
- tests
- created 2 new components `Accordion` which is made up of a group of `AccordionItem` components.
- the `Accordion` component simply controls the state of each `AccordionItem` and auto-closes others if `allowMultipleOpenItems` is set to `false` (default)
- the `AccordionItem` does all the heavy lifting and can be used independent of the parent `Accordion` component
- a mixed control approach was used for `AccordionItem` that allows it to be dumb (controlled) or manage its own state (uncontrolled) and these two modes are auto-determined based on whether the `opened` prop is utilized or not
- both components can set the prop `clickArea` to …
> feat(LOC-2671): create new Accordion component

- package.json
- src/components/modules/SiteInfoInnerPane/SiteInfoInnerPane.sass
This is a single line change that allows the "Site Overview" pane to scroll properly if there's too much content.
We used to need this to 'inherit' the overflow property, but thanks to Crum's work refactoring the tooltip, this is no longer an issue.
Also bumps version to `15.7.1`
Demonstrates scrolling and that tooltips still appear as expected
https://user-images.githubusercontent.com/7596682/108873353-abb70100-75c0-11eb-9ad8-077eadd4da27.mov
> feat(LOC-2652): allow site overview pane to scroll

- package.json
- src/components/alerts/Banner/Banner.tsx
This tiny PR bumps the local-components version and fixes an issue with Banners that removes an empty div from rendering if no icon is specified.
BEFORE: notice how the banner text is indented and not aligned left with the rest of the UI
AFTER: fixed!
Fixed in process of working through LOCAL-194: https://getflywheel.atlassian.net/browse/LOCAL-194
> fix: styling issue in banner component if no icon is present

- src/components/overlays/FlyModal/FlyModal.sass
- src/components/overlays/FlyModal/FlyModal.tsx
The warning icon was not displaying properly when trying to push changes to Flywheel with an incompatible WP version.
Remove top margin style from `FlyModal.sass` that was preventing the `topIcon` from displaying right. 
Before: 
After:
> Warning icon not displayed properly when trying to push WP 5.4.2 version

- package.json
- src/components/inputs/BasicInput/BasicInput.tsx
Quick PR that adds the basic input attributes as props to the BasicInput component. Pretty straightforward!
Reference doc: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text
Also bumps local-components version.
All the props added here are forwarded directly to the underlying "input" component, so no additional work is needed aside from adding the props directly.
> feat: update BasicInput component to accept standard input attributes as props

- src/components/loaders/ProgressRing/ProgressRing.scss
- src/components/loaders/ProgressRing/ProgressRing.stories.mdx
- src/components/loaders/ProgressRing/ProgressRing.tsx
This PR accomplishes a few things: 
- Update the `ProgressRing` circle colors in 'light' mode to match the design spec
- Pass decimals to `ProgressRing` stories instead of whole numbers
- Add ```width: auto !important;
height: auto !important;
margin: auto !important;``` to `ProgressRing_Svg` styles to overwrite the inherited styles from `ButtonBase`. Don't worry, this did not ruin styles for the existing `ProgressRing` in the app.
> chore: update ProgressRing styles

- src/components/overlays/Popup/Popup.sass
Small PR to accompany [this](https://github.com/getflywheel/flywheel-local/pull/1147). 
Removes pointer cursor from Popup component.
> fix: remove default pointer cursor from popup

- src/components/inputs/RadioBlock/RadioBlock.sass
##Summary 
A few styling tweaks to the RadioBlock disabled state
##Technical
- Updates z-index for the "selected" block that ensures it shows up "on top of" any buttons that have a tooltip wrapper
- Add opacity to disabled state
- Change cursor style to "not allowed"
##Screenshot 
Before: 
After: 
##Ticket Reference
https://wpengine.atlassian.net/browse/LOC-197
> feat: improve styling for RadioBlock disabled state

- package.json
- src/components/modules/VirtualList/VirtualList.tsx
- src/components/modules/VirtualTable/VirtualTable.tsx
Refactors `VirtualTable.tsx` to make the use of `extraData` more clear and unify the concept across components. Leverages `itemRendererExtraData` from `VirtualList` to prop-drill `extraData`, with a change in that component to react to changes in the `extraData` prop to force a re-render of the table body. 
This was done to make dynamically adjusting a cell's contents possible for a cloud backups ticket, where changes in internet connectivity affect a dropdown menu in a table cell.
> fix(LOC-2801): react to changes in extraData prop

- src/components/inputs/FlyDropdown/FlyDropdown.tsx
In the FlyDropdown component, makes the `useClickInsteadOfHover` prop to the Tooltip optional by making it a prop to FlyDropdown. Useful for when we want the dropdown to act more as a tooltip, for instance when dropdown is disabled when offline.
> feat(LOC-2801): optional hover for FlyDropdown

- package.json
- src/components/overlays/Tooltip/Tooltip.tsx
Add prop to conditionally hide tooltip so we don't have to keep duplicating code when using the `Tooltip` component.
> feat: add hideTooltip prop to conditionally hide tooltip

- src/components/inputs/CopyInput/CopyInput.scss
- src/components/inputs/CopyInput/CopyInput.tsx
- src/components/menus/Drawer/Drawer.scss
- src/components/menus/TertiaryNav/TertiaryNav.scss
This PR contains a few changes to some components that were necessary while completing [LOC-2981](https://wpengine.atlassian.net/browse/LOC-2981). The ugliest change here is nesting the scss in `CopyInput.scss` to allow for overriding the `TableList` styles, which is possible due to the global scoping of those classes.
Otherwise the git commits describe the changes - allowing for a drawer component in `TertiaryNav`, setting `visibility: hidden` when not showing the drawer to prevent a tabbing bug, and, most frustratingly, adding a background color to the drawer component. I spent forever wondering why that component was sitting behind the content, when actually it just didn't have a background 🥴
> feat(LOC-2981): changes for editing LiveLinks

- src/components/alerts/Banner/Banner.sass
- src/components/alerts/Banner/Banner.tsx
- src/components/inputs/CopyInput/CopyInput.scss
- src/components/inputs/CopyInput/CopyInput.tsx
- src/components/inputs/CopyInput/examples/CopyInputPlayground.tsx
This PR tweaks the CopyInput to change the message size and change the "readonly" state from using the "readonly" attribute to the "disabled" attribute. 
Also allows for removing stripes on the banner component and using the large close button instead of the smaller close icon.
> feat(LOC-2981): CopyInput and Banner tweaks

- src/components/buttons/RefreshButton/RefreshButton.scss
- src/components/inputs/CopyInput/CopyInput.scss
- src/components/inputs/CopyInput/CopyInput.tsx
- src/components/menus/TertiaryNav/TertiaryNav.tsx
This PR wraps the input field of `CopyInput` in an optional Tooltip and adds the `inputTooltipProps` prop, much like how the tooltip around the `CopyButton` component works.
This required applying much of the input CSS to the wrapping div, as it surrounds both the input field and the CopyButton component, which are now both surrounded by a ToolTipTargetContainer.
> feat(LOC-2986): add optional tooltip to CopyInput input field

- src/components/overlays/ScrollShadow/ScrollShadow.tsx
Moves the default props to the ScrollableContent, not the shadow overlay div, as we would generally want to target the content, not the shadow. Adds another prop to add a classname to the shadow div specifically.
> fix: move default props to content div, not shadow div

- src/components/inputs/BasicInput/BasicInput.tsx
Adds onKeyUp event handler to BasicInput (to allow for actions on certain keys, such as opening a link on hitting enter in an input)
> feat: add onKeyUp event handler to BasicInput

- src/components/buttons/CopyButton/CopyButton.tsx
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
- src/components/inputs/Switch/Switch.scss
- src/components/layout/AdvancedToggle/AdvancedToggle.sass
- src/components/layout/AdvancedToggle/AdvancedToggle.tsx
- src/components/loaders/DownloaderItem/DownloaderItem.tsx
- src/components/menus/TabNav/TabNav.sass
- src/components/modules/Markdown/Markdown.sass
- src/components/modules/VirtualTable/VirtualTable.tsx
- src/components/overlays/FlyTooltip/FlyTooltip.scss
- src/components/tables/TableList/TableList.sass
- src/styles/components/SettingsSidebar.scss
- src/styles/components/TabNav.scss
- src/styles/components/Tag.scss
- src/styles/containers/SiteInfo.scss
- src/styles/forms.scss
This pr removes hard-coded uppercase styles in Local Components and defaults components with optional text-transforms to `none` where applicable (usually the default would be `upper`).
> feat(LOC-3181): remove uppercase styles and dont default to optional uppercase

- src/styles/text.scss
This PR adjusts the global styles for anchor tags - in some places we have just raw HTML that renders (for example, the add-on descriptions or credits page). The only styles those can use are global styles, no React components. This PR brings the global styles in line with other efforts (accessible colors and unerline on hover by default).
> feat(LOC-3183): update global anchor styles for accessibility

- src/components/buttons/CopyButton/CopyButton.scss
- src/components/buttons/_private/ButtonBase/ButtonBase.scss
- src/components/inputs/FlyDropdown/FlyDropdown.scss
- src/components/inputs/InputPasswordToggle/InputPasswordToggle.scss
- src/components/inputs/Switch/Switch.scss
- src/components/layout/AdvancedToggle/AdvancedToggle.sass
- src/components/loaders/Spinner/Spinner.sass
- src/components/menus/ContextMenu/ContextMenu.scss
- src/components/menus/TabNav/TabNav.sass
- src/components/menus/TertiaryNav/TertiaryNav.scss
- src/components/modules/Card/Card.sass
- src/components/modules/EmptyArea/EmptyArea.sass
- src/components/modules/Markdown/Markdown.sass
- src/components/text/Text/Text.tsx
- src/components/text/Title/Title.tsx
- src/components/text/_private/TextBase/TextBase.scss
- src/components/text/_private/TextBase/TextBase.tsx
- src/styles/_partials/_theme.scss
- src/styles/_partials/_variables.scss
- src/styles/components/SettingsSidebar.scss
- src/styles/components/TabNav.scss
- src/styles/containers/SiteInfo.scss
- src/styles/forms.scss
This PR searches for `$gray25` and `$gray75` text in the app and in most cases replaces it with `gray` in light mode. I also made some small tweaks to other components to pass accessibility standards. In some cases I lightened the gray color used in dark mode as well.
> feat: update colors - mostly grays - for contrast compliance

- src/common/helpers/useDetectClickOrHoverWithinTargets.ts
- src/components/overlays/Tooltip/Tooltip.tsx
This PR fixes a bug where clicking the trigger element for a click-trigger tooltip opens the tooltip, but clicking inside the tooltip and clicking the trigger again doesn't close it until the second click. 
The tooltip component uses a custom function to set up hooks for the trigger and popper elements to determine whether to close or open the popper: `useDetectClickOrHoverWithinTargets`. When `useClickInsteadOfHover` is `true`, there are extra listeners and handlers to determine when to to close the popper using a state variable called `isClickFocus`.
6 months ago I consolidated the two separate functions into just this one, and introduced a bug where clicking the open popper messes up the state for `isClickFocus` for the trigger element. This PR adds another optional argument to the …
> fix: fix tooltip trigger on click

- src/components/buttons/TextButtonExternal/TextButtonExternal.stories.mdx
- src/components/buttons/TextButtonExternal/TextButtonExternal.tsx
- src/components/overlays/Tooltip/Tooltip.tsx
- src/index.ts
- src/styles/util.scss
This PR moves TextButtonExternal from Local core to Local Components. 
It also creates a utility class for site labels, which in Local Core were often just using `__Color__Green`, which conflicted with the updated styles.
Finally, I made a tweak to the tooltip `focus()` mechanism, so that it only focuses once when showing. Before, we were focusing it on every change to the popper element, which was pulling focus away from inputs in modals that were popped by the `ContextMenu` component.
> feat: TextButtonExternal and further tweaks

- src/components/menus/ContextMenu/ContextMenu.tsx
- src/components/overlays/Tooltip/Tooltip.tsx
The previous update to Local Components included a change to focus tooltips on opening. This PR makes that optional and only adds it to the ContextMenu component, since focusing all tooltips can interfere with some input events. For example, if entering a new LiveLinks username/password, that can get interrupted by just hovering over a tooltip. This caused functional tests to fail and is also a bad UX.
> fix: make tooltip focusing optional via prop

- src/components/buttons/_private/ButtonBase/ButtonBase.scss
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
- src/components/menus/ContextMenu/ContextMenu.scss
- src/components/menus/ContextMenu/ContextMenu.tsx
- src/styles/containers/AddSitePage.scss
This PR updates the button colors and SVG margins per design feedback and the Local design system Figma doc.
It also adds a prop to ContextMenu to make the background option for a more lowkey dropdown menu.
Finally, we adjust a global style that was tageting the "Heads up" message when downloading a lightning service.
> feat: update components per design review

- src/components/buttons/Close/Close.tsx
- src/components/overlays/ScrollShadow/ScrollShadow.scss
- src/components/overlays/ScrollShadow/ScrollShadow.tsx
This PR adds a z-index to the scroll shadow's shadow div. Also linted the ScrollShadow component. 
I attempted to do a larger refactor because implementing the scrollshadow component is pretty complicated and requires a wrapping div with `position: relative; overflow: hidden` on it, and the children contents to be contained in a single wrapping div. 
I was going to pull those wrappers into the ScrollShadow component, but it was really messing with existing implementations, so I may just tackle that in the future.
> fix: add z-index to scrollshadow shadow div

- src/components/inputs/RadioBlock/RadioBlock.sass
- src/components/menus/Stepper/Stepper.sass
- src/components/menus/Stepper/Stepper.tsx
This PR adds a `flex-grow: 1` to the `Step` component in `Stepper`. Before, we were calculating the width of the steps based on the number of steps, though I think this change will be much more flexible. Also, I think it still looks really good if the screen is small enough to start adapting to the size each individual step.
I also updated the component in general to a functional component using best practices. 
Also includes further tweaks to RadioBlock styling per Tyson's feedback.
> feat: update Stepper component and grow steps

- src/components/inputs/RadioBlock/RadioBlock.sass
- src/components/inputs/RadioBlock/RadioBlock.tsx
This PR adds yet another tweak to RadioBlock, since adding the justify-content center on the wrapper made the content on the atlas cards shrink. This PR makes that centering optional.
> feat: optionally center radioBlock content

- src/common/structures/IReactComponentProps.ts
- src/components/inputs/RadioBlock/RadioBlock.stories.mdx
- src/components/inputs/RadioBlock/RadioBlock.tsx
- src/components/menus/TertiaryNav/TertiaryNav.scss
- src/components/modules/Container/Container.tsx
- src/components/overlays/Tooltip/Tooltip.scss
- src/components/overlays/Tooltip/Tooltip.tsx
- src/components/tables/TableList/TableList.tsx
This PR adjusts the `RadioBlock` component once again! We were originally placing radio block options inside of an optional `Container` element, so I just moved the outer radio block option wrapper to that `Container` element. So now we will always render that `Container` (defaults to `div`), but we are still able to pass custom options to it. This makes adding a tooltip to a radio block option with content possible without style conflicts!
I also added a z-index to the tooltip popper container, because due to a bad bug fix for the user profile avatar showing up in front of overlayed window components, it was being hidden by a z-index of 10 on the `window` component. I created a ticket to tackle this problem more elegantly in the Popup component (use a tooltip or portal instead of a …
> feat: adjust radioblock container and add z-index to tooltip popper

- src/components/inputs/RadioBlock/RadioBlock.tsx
This PR is the last one to RadioBlock I swear. Fixes a "unique key in list" console error when using options without labels.
> fix: make radioBlockItem key the option value instead of label

- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
- src/components/inputs/BasicInput/BasicInput.tsx
- src/components/inputs/FlyDropdown/FlyDropdown.scss
- src/components/inputs/FlyDropdown/FlyDropdown.stories.mdx
- src/components/inputs/FlyDropdown/FlyDropdown.tsx
- src/components/inputs/RadioBlock/RadioBlock.sass
- src/components/overlays/FlyModal/FlyModal.sass
This PR fixes a bug that was caused by a bug fix in tooltip to a bug caused by a bad bug fix in popup to a bug caused by a z-index there. We've been bumping z-indexes and forgot this one :/ I also:
- Fixed a problem with the RadioBlock outline on hover with > 2 options
- Added a `selectedIcon` to `Flydropdown` for Cloud Backups - will just plop an icon to the left of the trigger TextButton, no real styles added
- Added a `disableStyle` to the `FlyDropdown` trigger `textButton`. Note it won't disable the whole Flydropdown, just make it look disabled.
- Refactired BasicInput to a function component and added `autofocus` capability with Refs!
> fix: increase z-index for FlyModal and more updates

- package.json
- webpack.common.js
- yarn.lock
This PR removes `dts-bundle-webpack` (a wrapper around `dts-bundle`), because I don't think we actually need it to generate a merged typings file. Actually, the `typings.d.ts` file that it was generating wasn't being used by the IDE because the `typings` field wasn't being set in `package.json`, so we really wont' feel this change. 
This should resolve a critical dependabot on `minimist`, or at least open the door for it, since this package was not being maintained.
> feat: remove dtsBundleWebpack

- package.json
- src/add-styles.ts
- yarn.lock
This PR removes the `url-parse` package from `package.json` (it's still installed as a dependency), and replaces it with the newer `URL` api available in browsers. Also includes a commit from dependabot to upgrade to a new minor version.
> feat: upgrade url-parse and remove it from package json

- package.json
- tsconfig.json
See this[ github issue for context on this fix](https://github.com/storybookjs/storybook/issues/16837#issuecomment-984006866). Essentially, Storybook 6.4 depends on `react-router-dom` v6, which includes a dependency on an updated version of `react-router` that includes typings. We're relying on a version that requires us to use `@types/react-router`, but the types in that package don't take precedence - `react-router` v6's `index.d.ts` does. 
The best fix would be to upgrade `react-router-dom`, but that would require more refactoring and more updates in Local core and maybe even add-ons. We could also update storybook to `v6.5`, but that is still in beta and will probably be a larger update with more problems. So until then, this should fix it, especially since we aren't compiling any …
> fix: fix react router typings with tsconfig path

- src/components/modules/VerticalNav/VerticalNav.tsx
- src/components/overlays/FlyModal/FlyModal.sass
- src/components/overlays/FlyModal/FlyModal.tsx
This PR refactors VerticalNav to be a Function Component and removes the SVG style overrides for the Close button in Flymodal.
> feat(LOC-3983): close icon FlyModal fix and vertical nav refactor

- .storybook/main.js
- .storybook/preview.tsx
- package.json
- tsconfig.json
- yarn.lock
This PR fixes issues with `react-router-dom` typings by upgrading to the latest beta version of storybook. See [this github issues for more context](see https://github.com/storybookjs/storybook/issues/16837#issuecomment-984006866). To completely resolve that issue I also had to remove the `storybook-addon-themes` plugin, but I've been here almost a year and never used the button that added to switch between light and dark mode, so now it just defaults to the split view.
There was also an issue where a `react-testing-library` is depending on `@types/react^17`, which causes our hoisted module to be `@types/react@16.14.26`, causing a mismatch between versions between Local Components and Core. So I decided to just bump it to that hoisted version in both repos, and that resolved those build …
> chore: upgrade sb, bump react types, remove theme addon

- package.json
- src/components/modules/VirtualTable/helpers/VirtualTableHelper.ts
- yarn.lock
This PR removes a dependency on @getflywheel/memoize-one-ts ([see that repo here](https://github.com/getflywheel/memoize-one-ts)). Looks like we forked that repo in order to rewrite it in Typescript and add decorators. However, the current version is mostly Typescript, so I just removed the decorator syntax in favor of wrapped arrow functions.
Seems like `VirtualList` and `VirtualTable` still work fine.
> feat: remove forked memoize-one dependency in favor of regular package

- jest.config.js
- package.json
- src/components/menus/TertiaryNav/TertiaryNav.tsx
- src/components/overlays/Tooltip/Tooltip.test.tsx
- yarn.lock
This PR addresses the 4 open dependabot tickets on this repo. It includes upgraded versions of the following: 
- Storybook (routine upgrade)
- Jest (to fix 2 dependabots) - required adding the `jest-environment-jsdom` package
- Typescript (to meet minimum peer dependency requirements)
The upgrades were very simple and required no fixes of any breaking changes. All tests still run after changing the jest environment to `jsdom`.
Added 2 resolutions to fix dependabot erros in `glob-parent` and `trim-newlines`
> feat: several upgrades for dependabots

- src/components/inputs/Combobox/Combobox.scss
- src/components/inputs/Combobox/Combobox.tsx
We switched up the focus approach when navigating via keyboard in Combobox, resulting in keyboard navigation that focused/hovered options without scrolling to them in a scrollable dropdown. I added a simple solution of using a callback ref to get access to the DOM element on every render, scrolling to the option if it is focused. 
I also changed the default `maxHeight` to 0 instead of undefined to prevent a glitch on initial render that caused the dropdown to fully expand before getting the `maxHeight` applied.
> fix: scroll to option when navigating via keyboard

- package.json
- src/common/structures/IReactComponentProps.ts
- src/components/inputs/RadioBlock/RadioBlock.tsx
- src/components/modules/Container/Container.tsx
We need to make RadioBlock more accessible. In the meantime, we need it to be selectable by PlayWright, to easily understand whether an option is selected or not via selectors. 
This PR re-enables the `aria-checked` attribute, which was originally being passed until I changed the wrapper component to `Container`.
> fix: reenable aria-checked on radioblock due to container component

- src/components/alerts/BannerCarousel/BannerCarousel.tsx
- src/components/alerts/BannerCarousel/BannerCarouselExample.tsx
This PR adds a few tweaks that solve a few bugs that cropped up while implementing the `BannerCarousel` with our MobX banner store in Local Core. 
Namely, banners were being added/removed so quickly that state wasn't getting set in time, which means `useEffect`s weren't seeing changes, and things like height weren't being properly set. I fixed this by setting the `gettingHeight` state variable inside of a `setTimeout` function - this is a hack to ensure things fire off synchronously. We can't just put the code for resetting the height inside of a function, because we're grabbing the height from a dummy DOM element that conditionally renders based on `gettingHeight`, and we need to watch for changes in that state variable to properly leverage `useLayoutEffect`. That way the right code is …
> feat: tweak BannerCarousel to shore up bugs when implemented

- package.json
- src/styles/containers/SiteInfo.scss
We are expanding the DownloaderOverlay in SiteInfo to cover the bottom bar, which has a popup element in the Live Links toggle that utilizes a z-index. 
This PR adds a z-index of 100 to the DownloaderOverlay, which I believe is one of the only reasonable use cases for z-index!
> fix: add z-index 100 to downloaderoverlay

- package.json
- src/components/inputs/BrowseInput/BrowseInput.tsx
- webpack.common.js
- yarn.lock
This is the only blocker for the Electron upgrade in Local Components. 
BrowseInput needs to access the remote module to launch a file Explorer dialog. I added the dependency to `package.json` - previously, `electron` didn't need to be a dependency because that was the target for webpack. However, since this is a separate package, we need the dependency - I tried just ignoring it in Webpack via that IgnorePlugin, but linking it up didn't work.
> feat: use @electron/remote for BrowseInput

- package.json
- src/components/tables/TableList/TableList.sass
- src/components/tables/TableList/TableList.stories.mdx
- src/components/tables/TableList/TableList.tsx
I had a PR that added in `vertical-align: middle` to child divs of `TableListRow` by default, but that made the preferences table in Core look really wonky. What I really want is an option to vertically align some table list rows. This PR adds that and spreads the style prop to `TableListRow`.
> fix: more robust tableListRow centering

- src/components/alerts/BannerCarousel/BannerCarousel.stories.mdx
- src/components/alerts/BannerCarousel/BannerCarousel.tsx
- src/components/alerts/BannerCarousel/BannerCarouselExample.tsx
The BannerCarousel is good, but it can be better!
This PR changes the carousel to use a `banners` prop instead of the `children` prop, so that we can see more clearly when the banners in the carousel have changed. This is easy because in Core we already have an array of this type that we modify in order to pass to BannerCarousel, so this will simplify things in core a little. 
I was previously just relying on a count, but sometimes the banners in a carousel will change without the number of banners changing. In that case, I had a stopgap to just update the children array, but when implemented in Core, we have a bunch of rerenders that would clear timeouts when switching between sites, for example. In that case the banner would just disappear while being hidden. 
With this change, the …
> feat: improve BannerCarousel to prevent extra rerenders

- src/components/alerts/ToastContainer/ToastContainer.tsx
Importing the toast styles causes problems when installed in Core due to our use of css modules. For some reason, adding an `exclude` field to core's webpack rules does not work! Luckily, `react-toastify` exports a function to inject the styles on demand. I am calling this once in the ToastContainer.tsx file, and that should just inject the styles once, if we place ToastContainer high enough (in App.tsx)
> fix: inject toast styles instead of importing them

- src/components/alerts/Toast/Toast.scss
- src/components/alerts/Toast/Toast.tsx
- src/components/alerts/ToastContainer/ToastContainer.tsx
The `injectStyles()` method provided by `react-toastify` injects the stylesheet at the bottom of `head` via `appendChild`. This is an issue, because in Core, the styles are added via a `link` tag before the injected styles, so the global `Toastify` style overrides are not taking precedence. 
I have opened an issue with the author of that repo [here](https://github.com/fkhadra/style2js/issues/1), but until we get the ability to change that injection method, I have created a workaround to essentially move the offending stylesheet up to the top of `head`. 
The `try/catch` is needed because some style sheets are inaccessible, and trying to access them will throw an error.
> fix: move toast styles to top of head

- package.json
- yarn.lock
This PR upgrades eslint-plugin-import to 2.27.4 in order to raise tsconfig-paths dep versions, thereby unblocking a json5@2.2.2 upgrade.
> chore(deps): upgrade json5 to 2.2.2

- src/common/structures/IReactComponentProps.ts
- src/components/layout/Accordion/AccordionItem.tsx
This PR adds better types to `IReactComponentProps`, specifically the handler functions, by pulling in types from React itself. Interfaces extending this interface can now optionally pass a generic type for the kind of HTMLElement, but just `HTMLElement` should be good for the type. I also added in `onContextMenu`. 
This approach of adding what we need when we need it is I think better than just extending `React.HTMLProps`, because that's a lot of props that we sometimes use the names of in our own components but with different types, so it would throw incorrect overload errors.
I also linted the `AccordianItem` component.
> feat: type out IReactComponentProps more accurately and add onContextMenu

- src/common/structures/IReactComponentProps.ts
- src/components/buttons/PrimaryButton/PrimaryButton.tsx
- src/components/buttons/ThreeDotButton/ThreeDotButton.scss
- src/components/buttons/ThreeDotButton/ThreeDotButton.stories.mdx
- src/components/buttons/ThreeDotButton/ThreeDotButton.tsx
- src/components/buttons/_private/ButtonBase/ButtonBase.scss
- src/components/menus/ContextMenu/ContextMenu.scss
- src/components/menus/ContextMenu/ContextMenu.tsx
- src/index.ts
For the Site Group work, we need the standalone three dot button from the `ContextMenu` component in order to trigger a system menu. This PR pulls that out into its own component.
I also use it in the `ContextMenu` component and just linted the `PrimaryButton` component.
> feat: Add ThreeDot button component

- src/components/layout/Accordion/AccordionItem.stories.mdx
- src/components/layout/Accordion/AccordionItem.tsx
We have a new IconButton component that handles placing an icon in a button tag, along with hover and active color states.
This commit pulls out the icon button render logic into a separate function and simplifies it a bit.
I also spread the ...restProps onto the wrapping div, giving us things like `onClick`, etc.
> feat: use IconButton in AccordianItem and spread rest of props

- src/common/structures/IReactComponentProps.ts
- src/components/buttons/ThreeDotButton/ThreeDotButton.scss
- src/components/buttons/_private/ButtonBase/ButtonBase.scss
- src/components/buttons/_private/ButtonBase/ButtonBase.tsx
- src/components/layout/Accordion/AccordionItem.tsx
These changes are necessary following feedback from Tyson on the Site Group work.
Includes:
- Accessibly changing the `AccordionItem` header from a `button` to a `div` when the `clickArea` is `"all"`.
- Optionally stopping the propagation of a button's `onKeyDown` handler via a new prop
- Gray mode color tweaks for `IconButton` (the only button using this color mode)
> feat: site group tweaks

- src/components/layout/Accordion/AccordionItem.tsx
Having the ability to pass a classname to these different parts will remove the need for global styles in Core. Also just best practice.
> feat: add props for custom classnames on the accordion item content and summary

- src/common/structures/IReactComponentProps.ts
- src/components/inputs/BasicInput/BasicInput.tsx
- src/index.ts
Also exports the BasicInput props and adds an onKeyDown event to IReactComponentProps.
> feat: add highlightText option to BasicInput

- src/components/inputs/IconCheckbox/IconCheckbox.scss
- src/components/inputs/IconCheckbox/IconCheckbox.tsx
- src/components/overlays/Popup/Popup.sass
- src/styles/_partials/_mixins.scss
- src/styles/base.scss
Cleans up the IconCheckbox and adds a focus state for keyboard navigation.
Changes the default outline for focused elements to $green (we've been wanting that for awhile)
Correctly selects any focused elements. I think Alexa had accidentally put an ampersand which was only selecting the body, not children.
> feat(LOC-3187): clean up IconCheckbox, Popup, and default outline for focus state

- src/components/inputs/IconCheckbox/IconCheckbox.scss
Oops! Focus-visible only shows on keyboard nav, which is what we want.
> fix: change focus in iconcheckbox to focus-visible

- package.json
- src/common/helpers/useDetectClickOrHoverWithinTargets.ts
- src/common/structures/global.d.ts
- src/components/menus/ContextMenu/ContextMenu.tsx
- src/components/overlays/Tooltip/Tooltip.scss
- src/components/overlays/Tooltip/Tooltip.stories.mdx
- src/components/overlays/Tooltip/Tooltip.tsx
- src/index.ts
- yarn.lock
This PR adds a method for closing a tooltip via a custom JS event. This is different than using the hideTooltip prop because we get the animations. 
Using hideTooltip and forceShow to mimic a controlled tooltip loses animations and the ability to still get the trigger, such as a click. Also, using both at the same time creates some wonkiness in the internal state (i.e. closing via the prop then opening and trying to close via the trigger doesn't work right away).
This is a workaround inspired by our `react-toastify` library - a JS event will dispatch state updates to the tooltip stage, triggering the closing animations. We also need to remove listeners for clicks on that event. It works well!
Finally, we close the ContextMenu on clicking any clickable item, something we've been wanting …
> feat: Close ContextMenu when clicking a clickable item

- src/styles/_partials/_mixins.scss
Does what it says!
I thought we'd need to disallow dragging on any buttons that were underneath the drag area, but something might have changed during an electron upgrade, because now we can click the buttons under the drag area while still dragging there too. I remember that not being the case when I originally changed this to 10px.
> fix: increase drag region

- package.json
- src/components/inputs/RadioBlock/RadioBlock.test.tsx
- src/utils/TestComponentPropUtils.tsx
- yarn.lock
Includes easy fixes for `dns-packet` and `webpack,` and resolution fixes for `terser` and `json5`.
Was hoping an upgrade to storybook would fix terser, but it didn't. Also, we're running out of upgrade space for storybook, looks like version 7.0 is out, but that'll require upgraded node. Should be a good time to re-evaluate our Storybook instance if we bring this inside Local Core.
> fix: close open dependabots

- src/components/modules/VerticalNav/VerticalNav.tsx
Labels are currently not associated with their buttons, so screenreader users hear prompts such as “link, image, app.html” instead of “Local Site” or “Blueprints”, making it very difficult to navigate Local. This includes the “Add Local site” button.
Instead, these should read:
- link, Local sites
- link, Connect
- link, Blueprints
- link, Add-ons
- link, Support,
- link, Add Local site
Uses the existing tooltip text to add `aria-label` to the `NavLink` for screen readers.
Should be tested with [this branch in flywheel-local](https://github.com/getflywheel/flywheel-local/tree/jb/LOC-5279/a11y-hide-svg).
To start (or stop) VoiceOver, press Command-F5. 
Before/After
Markup
- [LOC-5279](https://wpengine.atlassian.net/browse/LOC-5279)
- It's difficult to navigate local without other …
> Fix: Add aria-label to `NavLink` for improved a11y of main menu

- src/components/modules/VerticalNav/VerticalNav.tsx
- src/components/overlays/FlyTooltip/FlyTooltip.tsx
- As a `nav` instead of a div, it serves as a landmark for screen readers (and possible later improvement for keyboard navigation)
- Adds a title for use as an `aria-label` with the vertical nav
- When using arrow keys and a screen reader within the nav, this prevents the tooltip from being read out in addition to the `aria-label` on the link in the vertical nav
Should be tested with [this branch in flywheel-local](https://github.com/getflywheel/flywheel-local/tree/jb/fix/vertical-nav).
To start (or stop) VoiceOver, press Command-F5. 
Screen readers now see the `nav` as a landmark and the title/aria-label is read.
- [LOC-5321](https://wpengine.atlassian.net/browse/LOC-5321)
- The Avatar login tab & link popup is not accessible. [Issue in …
> Fix: Improve VerticalNav a11y

- src/components/inputs/Combobox/Combobox.scss
- src/components/inputs/Combobox/Combobox.stories.mdx
- src/components/inputs/Combobox/Combobox.tsx
- src/components/inputs/Combobox/ComboboxConnectExample.tsx
I'm going to try and add this component to Cloud backups for backup selection, but the dropdown gets hidden by the stepper, and the top component scrolls. This solution adds an option to adjust the max height, which is dynamically set to 75px above the bottom of the window and is reset on window resize.
> feat: add maxHeightOffest option for Combobox

- package.json
- src/components/menus/ContextMenu/ContextMenu.test.tsx
- src/components/menus/ContextMenu/ContextMenu.tsx
- src/utils/randomId.test.ts
- src/utils/randomId.ts
- yarn.lock
When linking the current master branch of local-components in development, our use of nanoid causes the error below and prevents Local from loading. (We have [not yet released this change in local-components](https://github.com/getflywheel/local-components/compare/17.7.2...master), which is why we have not seen it in Local itself yet.)
I removed `nanoid` and created a simple `randomId` function instead.
1. Downgrade from nanoid 5.x to 3.3.5: https://github.com/ai/nanoid/issues/422#issuecomment-1553393904
2. Refactor to use a dynamic import as the error output suggests (but this potentially infects all call sites with `await` and [recolors](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/) parent functions as async).
3. Switch from `"module": "commonjs"` to …
> deps: replace nanoid with randomId util
