src/components/DragBar/DragBar.sass
src/styles/_partials/_mixins.scss
src/styles/components/Window.scss
src/styles/containers/About.scss

**Audience:** Users
**Summary:** Fix padding issue for About page on Windows. Add top dragbar prior to React loading on Mac.
**Screenshot**:
(please disregard the 3 Mac dots seen at the top-left of the following screenshot)

improvement(LOC-270)(LOC-362): add polish and fix ui issues

---

src/components/RadioBlock/README.md
src/components/RadioBlock/RadioBlock.sass
src/components/RadioBlock/RadioBlock.tsx
src/styles/components/SitesSidebarSite.scss
src/styles/forms.scss

**Audience:** Users
**Summary:** This a bunch of various ui improvements and bugs that have been bundled up into a single PR. Including:
**Technical:**
* add warn state to RadioBlock
* fix FlySelect text/arrow overlap issue when in a form
* make placeholder text color for components consistent

improvements(ui-tweaks): make changes to a number of ui elements and issues

---

src/components/VerticalNav/components/WorkspaceSwitcher.scss

**Summary:** Adjust styles for avatar padding and horizontal position of links
**Screenshot:**

style(LOC-698): adjust avatar padding and center links

---

.github/workflows/publish-styleguidist.yml

**Summary:** Add `publish-styleguidist.yml` workflow for GitHub Actions to replace Bitrise.

Add publish-styleguidist.yml workflow

---

src/components/alerts/Banner/Banner.sass
src/components/buttons/_private/ButtonBase/ButtonBase.scss
src/components/inputs/BrowseInput/BrowseInput.tsx
src/components/inputs/RadioBlock/RadioBlock.tsx
src/components/menus/TabNav/TabNav.sass
src/components/modules/VerticalNav/README.md
src/components/modules/VerticalNav/components/WorkspaceSwitcher.tsx

**Summary:** Several regressions occurred after the component work. This addresses those issues specific to `local-components`.
**Technical:** Several improvements also made like separate disabled styles for secondary buttons.

fix(LOC-1273): fix ui regressions with new globals, button and text components

---

src/components/overlays/FlyModal/FlyModal.sass
src/styles/containers/SiteInfo.scss

**Summary:** The FlyModal and SiteInfo component styles need tweaks to accommodate the new Connect feature and this makes those minor changes.

style(LOC-1251): tweak modal and site info styles to accommodate new connect feature

---

src/components/modules/VerticalNav/VerticalNav.scss

Aligns the "Add Local Site" tooltip to the appropriate button.

fix(LOC-1000): Align "Add Local Site" tooltip to button.

---

src/components/modules/VerticalNav/VerticalNav.scss

fix(LOC-1000): Adjust spacing of tooltop

---

package.json

chore: bump to 13.2.1

---

package.json
src/styles/containers/SiteInfo.scss

**Audience**
Local users.
**Summary**
Update to CSS for site info overview page; this is needed to match new page structure (link length/color fix).

fix(LOC-1852): CSS restructuring for site overview layout.

---

src/components/modules/VerticalNav/components/WorkspaceSwitcher.scss
src/components/modules/VerticalNav/components/WorkspaceSwitcher.tsx

**Audience**
Local users.
**Summary**
Update to Workspace Switcher styles and structure. This introduces even padding between all sections (controls).

fix(LOC-1897): tweak to Workspace Switcher so section padding is even.

---

src/components/menus/TertiaryNav/TertiaryNav.tsx

`this.props.children` isn't a proper array so we need to get crafty with how to pull the first `<TertiaryNavItem />` so we can redirect to it.

fix: resolve type issue in <TertiaryNav />

---

README.md

Add documentation to `README.md` for component and style systems.

chore(LOC-1889): update README to include more component and style system details

---

src/components/inputs/BrowseInput/BrowseInput.tsx
src/components/inputs/Checkbox/Checkbox.tsx
src/components/inputs/RadioBlock/RadioBlock.tsx
src/components/inputs/Switch/Switch.tsx
src/components/media/Avatar/Avatar.tsx
src/components/menus/Drawer/Drawer.tsx
src/components/modules/VirtualList/VirtualList.tsx
src/components/tables/TableListMultiDisplay/TableListMultiDisplay.tsx
src/components/tables/TableListRepeater/TableListRepeater.tsx

As part of the effort to remove warnings from the dev console I renamed `componentWillReceiveProps` with UNSAFE_

Prepend componentWillReceiveProps with UNSAFE_

---

src/components/alerts/Banner/Banner.sass
src/components/alerts/Banner/Banner.tsx

feat: add height prop to Banner

---

package.json
src/components/alerts/OfflineBanner/OfflineBanner.scss
src/components/alerts/OfflineBanner/OfflineBanner.stories.mdx
src/components/alerts/OfflineBanner/OfflineBanner.test.tsx
src/components/alerts/OfflineBanner/OfflineBanner.tsx
src/components/icons/Icons.tsx
src/components/icons/svgs/OfflineIcon.tsx
src/index.ts
src/svg/offline.svg

Add `OfflineBanner` component.

feat(LOC-2805): add OfflineBanner component

---

src/components/buttons/RefreshButton/RefreshButton.scss
src/components/buttons/RefreshButton/RefreshButton.stories.mdx
src/components/buttons/RefreshButton/RefreshButton.test.tsx
src/components/buttons/RefreshButton/RefreshButton.tsx
src/index.ts

This PR adds a refresh button - was easier than trying to do it by hand in the app due to styling issues/separation of code. I think it makes sense to have a separate component for this.

feat(LOC-2979): added RefreshButton component

---

src/components/overlays/FlyModal/FlyModal.tsx

feat: optionally show close button on FlyModal

---

src/components/inputs/FlySelect/FlySelect.scss
src/components/inputs/FlySelect/FlySelect.tsx
src/styles/forms.scss

This pr updates the flyselect dropdown to match our accessibility work, including changing svg color on hover and modifying the options colors.

feat(LOC-3183): update flyselect colors for accesibility

---

src/components/inputs/FlyDropdown/FlyDropdown.scss

This updates the colors of FlyDropDown items to match the accessibility color scheme of buttons

feat(LOC-3183): update flydropdown item to match accesibility color scheme

---

src/components/modules/Markdown/Markdown.sass

refactor: use mixin

---

src/components/alerts/Banner/Banner.tsx
src/components/buttons/TextButtonExternal/TextButtonExternal.tsx
src/components/buttons/_private/ButtonBase/ButtonBase.scss
src/components/inputs/Checkbox/Checkbox.sass
src/components/inputs/Switch/Switch.scss
src/components/menus/ContextMenu/ContextMenu.tsx
src/components/menus/TertiaryNav/TertiaryNav.scss
src/components/modules/Card/Card.sass
src/components/modules/Markdown/Markdown.sass
src/styles/_partials/_mixins.scss
src/styles/containers/Flywheel.scss

This PR adds a few changes that came up during a call with Tyson where we discussed the UI refresh work. 
The commit messages are pretty descriptive of what was done!

feat: various updates per design review feedback

---

.eslintrc.json
src/common/helpers/useDetectClickOrHoverWithinTargets.ts
src/components/inputs/RadioBlock/RadioBlock.sass
src/components/inputs/RadioBlock/RadioBlock.stories.mdx
src/components/inputs/RadioBlock/RadioBlock.tsx
src/components/menus/ContextMenu/ContextMenu.tsx
src/styles/containers/AddSitePage.scss

This PR adds some additional changes to RadioBlock, and also changes the default background of the global AddSite class. Also included are some linting of files - pls ignore whitespace changes

feat: update radioBlock and addsite background

---

package.json

chore: bump to 17.6.0

---

src/components/tables/TableList/TableList.sass

Wow this is my first time touching these TableList styles and they are so convoluted and hard to follow. But adding this vertical align for the table-cell div children really makes things look a lot nicer, especially One Click Admin and the new Xdebug toggle.

feat: align table list row div child to middle

---

package.json
yarn.lock

PR to update Storybook and add a resolution for `loader-utils` to fix Dependabot alert

security: add resolution for loader-utils to resolve dependabot

---

src/styles/_partials/_theme.scss

Doesn't change the input theme borders, so it adds another param to the mixin.

feat(LOC-4830): Increase border width to 2px in the border theme helpers

---

src/styles/_partials/_variables.scss

Per design feedback now that borders are thicker, we can have them slightly darker

feat: change dark mode border color to graydark-50

---

package.json

chore: bump to 17.7.1

---

package.json

chore: bump to 17.7.2
